---
- name: Export .zshrc to ansible_user
  ansible.builtin.copy:
    src: ~/.zshrc
    dest: /home/dave/.zshrc
    owner: dave
    group: dave
    mode: '0755'

- name: Export pretty markdown
  ansible.builtin.copy:
    src: /home/sam/dev/random/ansible/bootstrap/includes/flag.md
    dest: /home/dave/README.md
    owner: dave
    group: dave
    mode: '0644'

- name: Show README.md on pts0
  become: true
  ansible.builtin.shell: |
    cat /home/dave/README.md > /dev/pts/0 2>/dev/null
  changed_when: true
  failed_when: false
